### ISSUE TITLE
myCrashVariant User Manual project v1.0

### ISSUE THREAD

**Issue by rafavaliev** [sintah/INPLS-SED-2017-g05#14]
The last part of user manual document

- [x] 2.4.1 Actors and functionalities

- [x] 3. Usage Guide

- [ ] 4. Software operations

- [ ] Appendix 1.

**Comment by sintah** [comment]
2.4.1 Actors and fucntionalities - Timur done

**Comment by TimurKasatkin** [comment]
2.4.1 Actors and functionalities - **done**

**Comment by TimurKasatkin** [comment]
3. Usage Guide - **done**

**Comment by rafavaliev** [comment]
TimurKasatkin - 4. Software operations **done** partialy witout mockups
